import type { Metadata } from "next";
import { Bebas_Neue, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import DesktopNav from "./components/navigation/DesktopNav";
import Footer from "./components/navigation/Footer";
import FloatingPopover from "@/components/ui/floating-popover";
import { CartProvider } from "./core/cartContext";
import { Toaster } from "@/components/ui/sonner";
import MobileNav from "./components/navigation/MobileNav";

const fontSans = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
});

const fontHeading = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-heading",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <CartProvider>
          <div className="hidden md:block">
            <DesktopNav />
          </div>
          <div className="block md:hidden">
            <MobileNav />
          </div>
          {children}
          <Footer />
          <FloatingPopover />
        </CartProvider>
        <Toaster />
      </body>
    </html>
  );
}
